# Generated by Django 5.2.6 on 2025-09-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='replies_from_others',
            field=models.TextField(default='none'),
        ),
    ]
