# Generated by Django 5.2.6 on 2025-09-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_alter_car_door_numb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='make',
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('gas', 'Gas'), ('diesel', 'Diesel'), ('hybird', 'Hybrid'), ('lp_gas', 'LP Gas')], default='gas'),
        ),
    ]
